cities:
  - Babno Polje
#  - Bilje pri Novi Gorici
  - Blegoš
#  - Bohinjska Češnjica
#  - Boršt Gorenja vas
#  - Bukovski vrh
#  - Cerkniško jezero
#  - Davča
  - Debeli Rtič (Zora)
#  - Gačnik
#  - Godnje
#  - Gornji Grad
#  - Hočko Pohorje
  - Hrastnik
  - Idrija
#  - Iskrba
#  - Jeronim
#  - Jeruzalem
  - Jezersko
#  - Kamniška Bistrica
  - Kanin
  - Kočevje
#  - Korensko sedlo
  - Kranj
  - Kredarica
#  - Krn
#  - Krvavec
#  - Kubed
  - Kum
  - Letališče Jožeta Pučnika Ljubljana
#  - Lisca
  - Litija
  - Ljubljana
  - Logarska dolina
  - Logatec
  - Maribor
#  - Marinča vas
#  - Metlika
#  - Mežica
#  - Miklavž na Gorjancih
  - Murska Sobota
  - Nanos
  - Nova Gorica
#  - Nova vas - Bloke
  - Novo mesto
#  - Osilnica
#  - Otlica
#  - Pasja ravan
#  - Pavličevo sedlo
#  - Planina pod Golico
#  - Podnanos
  - Postojna
#  - Predel
  - Ptuj
#  - Radegunda
  - Rogaška Slatina
  - Rogla
#  - Rudno polje
#  - Sevno
#  - Slavnik
#  - Slovenske Konjice
#  - Sveti Trije Kralji na Pohorju
#  - Sviščaki
#  - Šebreljski vrh
#  - Šmartno pri Slovenj Gradcu
#  - Tatre
  - Tolmin - Volče
#  - Topol
#  - Trbovlje
  - Trebnje
  - Trojane - Limovce
  - Tržaški zaliv (Zarja)
#  - Uršlja gora
#  - Vedrijan
  - Velenje
#  - Velike Lašče
  - Vogel
  - Vrhnika
  - Vršič
#  - Zadlog
#  - Zelenica
#  - Zgornja Kapla
#  - Zgornja Radovna
#  - Zgornja Sorica
